using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StoicTrade.Api.Services;
using StoicTrade.Api.Services.Strategies;
using System.Linq;
using System.Threading.Tasks;

namespace StoicTrade.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class EngineController : ControllerBase
    {
        private readonly FyersApiService _fyersApi;

        private readonly StoicTrade.Api.Data.AppDbContext _dbContext;

        public EngineController(FyersApiService fyersApi, StoicTrade.Api.Data.AppDbContext dbContext)
        {
            _fyersApi = fyersApi;
            _dbContext = dbContext;
        }

        [HttpGet("status")]
        public IActionResult GetStatus()
        {
            return Ok(new { IsRunning = _fyersApi.IsEngineRunning });
        }

        [HttpPost("start")]
        public IActionResult StartEngine()
        {
            // If already authenticated with Fyers, start engine directly
            if (!string.IsNullOrEmpty(_fyersApi.GetAccessToken()))
            {
                _fyersApi.StartPaperEngine();
                return Ok(new { Message = "Engine started successfully with live broker market data.", IsRunning = true });
            }

            // If no active Fyers token, redirect to Fyers OAuth to fetch real live broker quotes
            var authUrl = _fyersApi.GetAuthUrl();
            return Ok(new { Message = "Please authenticate with Fyers to connect live market data.", AuthUrl = authUrl });
        }

        [HttpPost("callback")]
        public async Task<IActionResult> AuthCallback([FromBody] AuthCallbackRequest request)
        {
            try
            {
                var token = await _fyersApi.ValidateAuthCodeAsync(request.AuthCode);
                return Ok(new { Message = "Engine started successfully. Connected to Fyers API.", Token = token });
            }
            catch (System.Exception ex)
            {
                return StatusCode(500, new { Error = "Failed to start engine: " + ex.Message });
            }
        }

        [HttpPost("stop")]
        public IActionResult StopEngine()
        {
            _fyersApi.Disconnect();
            return Ok(new { Message = "Engine stopped successfully.", IsRunning = false });
        }

        [HttpPost("squareoff")]
        [Authorize]
        public async Task<IActionResult> ManualSquareOff([FromServices] OrderManagementService orderManager)
        {
            int closed = await orderManager.AutoSquareOffAllPositionsAsync("Manual_UI_SquareOff");
            return Ok(new { Message = $"Square-off completed. Closed {closed} positions." });
        }

        /// <summary>
        /// Returns the last 50 signals generated by the strategy engine, newest-first.
        /// The frontend polls this endpoint to show live signal history on the Strategy Analysis page.
        /// </summary>
        [HttpGet("signals")]
        [Authorize]
        public IActionResult GetRecentSignals()
        {
            var signals = StrategyEngineService.RecentSignals
                .OrderByDescending(s => s.GeneratedAt)
                .Take(50)
                .ToList();
            return Ok(signals);
        }
    }

    public class AuthCallbackRequest
    {
        public string AuthCode { get; set; } = string.Empty;
    }
}

